pull_request_rules:
  - name: auto-merge
    conditions:
      - "author=@mirth-lang/collaborators"
      - "#status-failure<=0"
      - "#status-success>=10"
    actions:
      merge:
        method: squash
      delete_head_branch:
        force: False
