/* C99 autogenerated by mirth compiler */
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <fcntl.h>
#include <unistd.h>

#define STACK_SIZE 2000

size_t sc = STACK_SIZE;
int64_t stack[STACK_SIZE];

int64_t pop (void) {
    if (sc < STACK_SIZE) {
        return stack[sc++];
    } else {
        fprintf(stderr, "STACK UNDERFLOW");
        fputc(stderr, 10);
        exit(1);
    }
}

void push (int64_t x) {
    if (sc > 0) {
        stack[--sc] = x;
    } else {
        fprintf(stderr, "STACK OVERFLOW");
        fputc(stderr, 10);
        exit(1);
    }
}

// id
void w1 (void) {
}

// dup
void w2 (void) {
    int64_t x = pop();
    push(x); push(x);
}

// drop
void w3 (void) {
    pop();
}

// swap
void w4 (void) {
    int64_t x = pop();
    int64_t y = pop();
    push(x); push(y);
}

int main (int argc, char* argv) {
    return 0;
}
